"""
Hill coefficient sweep for a DSGRN parameter region.

Sweeps over Hill coefficients d for a network with L, U, T, gamma
loaded from parameter CSVs (generated by generate_dsgrn_params.py).
Supports two modes:
  - 'uniform': single d applied to all edges (original behavior)
  - 'per_edge': independent d_ij per edge, swept via itertools.product
Generates phase portraits and trajectory data for each combo,
plus a comparison figure in uniform mode.
"""

import sys
import itertools
from pathlib import Path

# Add src/ to path for bare imports
ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from network_parser import parse_net_spec, topology_slug
from data_generator import generate_trajectories, generate_ics_lhs
from utils import plot_phase_portrait, next_run_id

# ---------- Network & parameter region ----------
PAR_INDEX = 752
NET_SPEC = "1 : 1+2\n2 : (~1)2"
NETWORK_ID = None  # None = auto-generate slug from topology


def load_parameters(par_index, network_id, net_spec):
    """Load L, U, T, gamma from parameter CSVs."""
    params_dir = ROOT / "results" / "dsgrn_parameters" / network_id
    edges_path = params_dir / f"{par_index}_parameters_edges.csv"
    gamma_path = params_dir / f"{par_index}_parameters_gamma.csv"

    for p in (edges_path, gamma_path):
        if not p.exists():
            raise FileNotFoundError(
                f"Parameter file not found: {p}\n"
                f"Run generate_dsgrn_params.py first."
            )

    edges_df = pd.read_csv(edges_path)
    gamma_df = pd.read_csv(gamma_path)
    n = parse_net_spec(net_spec).n_nodes
    L = np.zeros((n, n))
    U = np.zeros((n, n))
    T = np.zeros((n, n))
    for _, row in edges_df.iterrows():
        s, t = int(row['source']), int(row['target'])
        L[s, t] = row['L']
        U[s, t] = row['U']
        T[s, t] = row['T']
    gamma = gamma_df['gamma'].values
    return L, U, T, gamma

# ---------- Sweep configuration ----------
MODE = 'uniform'  # 'uniform' or 'per_edge'

# Uniform mode: d_ij = d for all edges
D_UNIFORM = [2, 3, 5, 7, 11, 13]

# Per-edge mode: independent value list per edge (i, j)
D_PER_EDGE = {
    (0, 0): [2, 5, 10],
    (0, 1): [2, 5, 10],
    (1, 0): [2, 5, 10],
    (1, 1): [2, 5, 10],
}

N_TRAJ = 30
T_SPAN = (0.0, 10.0)
N_POINTS = 300
SEED = 42

OUTPUT_DIR = ROOT / "results" / "hill_sweep" / str(PAR_INDEX)  # used only by main()


def sweep_iterable(mode='uniform', d_uniform=None, d_per_edge=None):
    """Yield (label, steepness_matrix) for each sweep combination."""
    if mode == 'uniform':
        d_values = d_uniform or D_UNIFORM
        for d in d_values:
            label = f"d{d}"
            steepness = np.full((2, 2), float(d))
            yield label, steepness
    elif mode == 'per_edge':
        edges_dict = d_per_edge or D_PER_EDGE
        edges = sorted(edges_dict.keys())
        value_lists = [edges_dict[e] for e in edges]
        for combo in itertools.product(*value_lists):
            label = "_".join(str(v) for v in combo)
            steepness = np.zeros((2, 2))
            for (i, j), v in zip(edges, combo):
                steepness[i, j] = float(v)
            yield label, steepness
    else:
        raise ValueError(f"Unknown mode: {mode!r}")


def save_parameters(output_dir, topology, L, U, T, gamma):
    """Save L, U, T, gamma as a tidy CSV indexed by (source, target) edge."""
    rows = []
    for edge in topology.edges:
        s, t = edge.source, edge.target
        rows.append({
            'source': s, 'target': t,
            'L': L[s, t], 'U': U[s, t], 'T': T[s, t],
        })
    params_df = pd.DataFrame(rows)
    gamma_df = pd.DataFrame({'node': range(len(gamma)), 'gamma': gamma})
    params_df.to_csv(output_dir / "parameters_edges.csv", index=False)
    gamma_df.to_csv(output_dir / "parameters_gamma.csv", index=False)
    print(f"  Saved parameters_edges.csv, parameters_gamma.csv")


def run_sweep(par_index, net_spec, network_id, d_values=None,
              n_traj=30, t_span=(0.0, 10.0), n_points=300, seed=42,
              output_dir=None):
    """
    Run hill coefficient sweep for a single par_index.

    Args:
        par_index: DSGRN parameter index
        net_spec: DSGRN network specification string
        network_id: slug for parameter CSV directory
        d_values: list of uniform Hill coefficients (default: D_UNIFORM)
        n_traj: number of trajectories per d value
        t_span: integration time span
        n_points: number of time points
        seed: random seed for IC generation
        output_dir: explicit output directory (default: results/hill_sweep/{par_index})
    """
    d_values = d_values or D_UNIFORM
    topology = parse_net_spec(net_spec)
    L, U, T, gamma = load_parameters(par_index, network_id, net_spec)

    if output_dir is None:
        output_dir = ROOT / "results" / "hill_sweep" / str(par_index)
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    box = topology.trapping_box(U, gamma)

    save_parameters(output_dir, topology, L, U, T, gamma)

    # Fixed ICs across all d values
    ic_bounds = [(0.0, b) for b in box]
    ics = generate_ics_lhs(n_traj, n_dims=topology.n_nodes, bounds=ic_bounds, seed=seed)

    traj_dir = output_dir / "trajectories"
    phase_dir = output_dir / "phase_portraits"
    traj_dir.mkdir(parents=True, exist_ok=True)
    phase_dir.mkdir(parents=True, exist_ok=True)

    sweep = list(sweep_iterable(mode='uniform', d_uniform=d_values))
    all_data = {}

    for label, steepness in sweep:
        print(f"  --- {label} ---")

        data_df, _ = generate_trajectories(
            topology, L, U, T, gamma,
            approx_type='hill',
            steepness=steepness,
            n_traj=n_traj,
            t_span=t_span,
            n_points=n_points,
            ics=ics,
        )
        all_data[label] = data_df

        csv_path = traj_dir / f"{label}.csv"
        data_df.to_csv(csv_path, index=False)
        print(f"    Saved {csv_path.name}")

        png_path = phase_dir / f"{label}.png"
        plot_phase_portrait(
            topology, L, U, T, gamma,
            approx_type='hill',
            steepness=steepness,
            trajectories=data_df,
            ics=None,
            trapping_box=box,
            n_grid=30,
            save_path=str(png_path),
        )
        print(f"    Saved {png_path.name}")

    # Comparison figure
    _make_comparison_figure(sweep, all_data, topology, L, U, T, gamma,
                            box, d_values, par_index, phase_dir)


def _make_comparison_figure(sweep, all_data, topology, L, U, T, gamma,
                            box, d_values, par_index, phase_dir):
    """Generate the multi-panel comparison figure for uniform sweep."""
    from ode_builder import build_ode_rhs_np

    n_cols = 3
    n_rows = (len(sweep) + n_cols - 1) // n_cols
    fig, axes = plt.subplots(n_rows, n_cols, figsize=(7 * n_cols, 6 * n_rows))
    axes = np.atleast_2d(axes)

    B0, B1 = box[0], box[1]
    n_grid = 30
    x0_grid = np.linspace(0.01, B0 * 1.05, n_grid)
    x1_grid = np.linspace(0.01, B1 * 1.05, n_grid)
    X0, X1 = np.meshgrid(x0_grid, x1_grid)

    for idx, (label, steepness) in enumerate(sweep):
        row, col = divmod(idx, n_cols)
        ax = axes[row, col]

        rhs_fn = build_ode_rhs_np(topology, L, U, T, gamma, 'hill', steepness)

        DX0 = np.zeros_like(X0)
        DX1 = np.zeros_like(X1)
        for i in range(n_grid):
            for j in range(n_grid):
                dy = rhs_fn(0, [X0[i, j], X1[i, j]])
                DX0[i, j], DX1[i, j] = dy[0], dy[1]

        ax.streamplot(x0_grid, x1_grid, DX0, DX1, color='#555555',
                      linewidth=0.8, density=1.5, arrowsize=1.0)

        # Nullclines on a finer grid
        n_null = 500
        x0_fine = np.linspace(0.01, B0 * 1.05, n_null)
        x1_fine = np.linspace(0.01, B1 * 1.05, n_null)
        X0f, X1f = np.meshgrid(x0_fine, x1_fine)
        DX0f = np.zeros_like(X0f)
        DX1f = np.zeros_like(X1f)
        for ii in range(n_null):
            for jj in range(n_null):
                dy = rhs_fn(0, [X0f[ii, jj], X1f[ii, jj]])
                DX0f[ii, jj], DX1f[ii, jj] = dy[0], dy[1]
        ax.contour(X0f, X1f, DX0f, levels=[0], colors='#e41a1c', linewidths=1.5)
        ax.contour(X0f, X1f, DX1f, levels=[0], colors='#377eb8', linewidths=1.5)
        ax.plot([], [], color='#e41a1c', linewidth=1.5, label="$x_0' = 0$")
        ax.plot([], [], color='#377eb8', linewidth=1.5, label="$x_1' = 0$")

        # Overlay trajectories
        data_df = all_data[label]
        for tid in data_df['traj_id'].unique():
            traj = data_df[data_df['traj_id'] == tid]
            ax.plot(traj['x0'], traj['x1'], 'k-', alpha=0.35, linewidth=0.8)

        # Threshold lines
        for s in range(2):
            for t_idx in range(2):
                if T[s, t_idx] > 0:
                    if s == 0:
                        ax.axvline(T[s, t_idx], color='white', ls='--', alpha=0.7)
                    else:
                        ax.axhline(T[s, t_idx], color='white', ls='--', alpha=0.7)

        ax.set_xlim(0, B0 * 1.05)
        ax.set_ylim(0, B1 * 1.05)
        ax.set_xlabel('$x_0$')
        ax.set_ylabel('$x_1$')
        ax.set_title(f'$d = {d_values[idx]}$', fontsize=14)
        ax.legend(fontsize=7)

    # Hide unused subplots
    for idx in range(len(sweep), n_rows * n_cols):
        row, col = divmod(idx, n_cols)
        axes[row, col].set_visible(False)

    fig.suptitle(f'Hill Coefficient Sweep (par_index={par_index})', fontsize=16, fontweight='bold')
    plt.tight_layout()
    comp_path = phase_dir / "comparison.png"
    fig.savefig(comp_path, dpi=150, bbox_inches='tight')
    plt.close(fig)
    print(f"  Saved comparison figure: {comp_path}")


def main():
    topology = parse_net_spec(NET_SPEC)
    network_id = NETWORK_ID or topology_slug(topology)

    run_sweep(PAR_INDEX, NET_SPEC, network_id,
              d_values=D_UNIFORM, n_traj=N_TRAJ, t_span=T_SPAN,
              n_points=N_POINTS, seed=SEED)


if __name__ == "__main__":
    main()
